// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-qpfOMyJX3ae-FL74ViHd4TWKtECYUHI',
    appId: '1:1003310142314:web:48c7d78f2979423fa6cb13',
    messagingSenderId: '1003310142314',
    projectId: 'proj-739cf',
    authDomain: 'proj-739cf.firebaseapp.com',
    storageBucket: 'proj-739cf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAslxO27Kkhl5yZZrm0jocpp2mN2g2B3bo',
    appId: '1:1003310142314:android:c47c8698ef22d370a6cb13',
    messagingSenderId: '1003310142314',
    projectId: 'proj-739cf',
    storageBucket: 'proj-739cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwsPCrmBmniuikn90xnqhESstizZ1yvMA',
    appId: '1:1003310142314:ios:526b03f4450e8e96a6cb13',
    messagingSenderId: '1003310142314',
    projectId: 'proj-739cf',
    storageBucket: 'proj-739cf.firebasestorage.app',
    iosClientId: '1003310142314-3mgcrli4lumc8vt8g8bfbeet8f3o9qmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.aptcoder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwsPCrmBmniuikn90xnqhESstizZ1yvMA',
    appId: '1:1003310142314:ios:526b03f4450e8e96a6cb13',
    messagingSenderId: '1003310142314',
    projectId: 'proj-739cf',
    storageBucket: 'proj-739cf.firebasestorage.app',
    iosClientId: '1003310142314-3mgcrli4lumc8vt8g8bfbeet8f3o9qmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.aptcoder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-qpfOMyJX3ae-FL74ViHd4TWKtECYUHI',
    appId: '1:1003310142314:web:bb8dc5ae2cdb2f15a6cb13',
    messagingSenderId: '1003310142314',
    projectId: 'proj-739cf',
    authDomain: 'proj-739cf.firebaseapp.com',
    storageBucket: 'proj-739cf.firebasestorage.app',
  );
}
